c:\tools\nuget\nuget.exe pack Dragon.CPR.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Data.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Mail.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Mail.SqlQueue.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Files.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Files.MVC.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Files.S3.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Security.Hmac.Core.nuspec
c:\tools\nuget\nuget.exe pack Dragon.Security.Hmac.Module.nuspec